# Pages CMS configuration for Anton's Astro site
# Docs: https://pagescms.org/docs/configuration/

# ---------------------------------------------------------------------------
# MEDIA
# Uploaded images are saved in src/assets/images and referenced as /images/…
# ---------------------------------------------------------------------------
media:
  input: src/assets/images
  output: /images
  extensions: [ png, jpg, jpeg, webp, svg ]

# ---------------------------------------------------------------------------
# CONTENT TYPES
# ---------------------------------------------------------------------------
content:
  # ───── Blog articles ─────
  - name: articles
    label: Articles
    type: collection
    path: src/content/articles
    filename: "{year}-{month}-{day}-{slug}.mdx"

    view:
      fields: [ title, date, slug ]
      primary: title
      sort: [ date, title ]

    fields:
      - name: slug
        label: Slug
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: date
        label: Publish date
        type: date
        required: true
      - name: readingTime
        label: Reading time (min)
        type: number
      - name: body
        label: Body
        type: rich-text

  # ───── Site pages ─────
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename: "{slug}.mdx"

    view:
      fields: [ title, slug ]
      primary: title
      sort: [ title ]

    fields:
      - name: slug
        label: Slug
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Body
        type: rich-text

# End of .pages.yml
