# Pages CMS configuration for Anton's Astro site
# Docs: https://pagescms.org/docs/configuration/

# ---------------------------------------------------------------------------
# MEDIA
# Uploaded images will be stored in the repo under src/assets/images
# and referenced in markdown as /images/... so Astro can copy them as‑is.
# ---------------------------------------------------------------------------
media:
  input: src/assets/images
  output: /images
  extensions: [ png, jpg, jpeg, webp, svg ]

# ---------------------------------------------------------------------------
# CONTENT TYPES
# Currently the site only declares one Astro content collection: "articles".
# This mirrors /src/content/articles where all .mdx files live.
# ---------------------------------------------------------------------------
content:
  - name: articles            # machine name (unique)
    label: Articles           # shown in Pages CMS sidebar
    type: collection
    path: src/content/articles
    filename: "{year}-{month}-{day}-{slug}.mdx"  # create new posts as MDX

    view:
      fields: [ title, date, slug ]
      primary: title
      sort: [ date, title ]

    fields:
      - name: slug
        label: Slug
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: date
        label: Publish date
        type: date
        required: true
      - name: readingTime
        label: Reading time (min)
        type: number
      - name: body
        label: Body
        type: rich-text

# End of .pages.yml
