[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"] 