[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["dist/**/*", "public/**/*"] 