[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[dev]
  framework = "astro"
  targetPort = 3000

[[redirects]]
  from = "/writing/*"
  to = "/articles/:splat"
  status = 301
  force = true 