[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/fonts/*"
  to = "/fonts/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"] 