backend:
  name: git-gateway
  branch: main

media_folder: "public/images/articles"
public_folder: "/images/articles"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    extension: "mdx"
    format: "frontmatter"
    identifier_field: "slug"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Reading Time", name: "readingTime", widget: "number" }
      - { label: "Layout", name: "layout", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string", hint: "Will be used in the URL. Example: my-article-title" }
      - { label: "Body", name: "body", widget: "markdown", hint: "Supports MDX syntax" }
    summary: "{{title}} - {{date}}"
    sortable_fields: ["date", "title"]
    view_filters:
      - label: "Draft Articles"
        field: "draft"
        pattern: true
      - label: "Published Articles"
        field: "draft"
        pattern: false 